### ISSUE TITLE
testseb

### ISSUE THREAD

**Issue by ss1043** [ss1043/demo#1]
- [x] Updated software branding to reflect the new CI  [Proemion/legacy-windows-software#329](Proemion/legacy-windows-software#329)
- [ ]     Added support for logging J1939 messages [Proemion/legacy-windows-software#364](Proemion/legacy-windows-software#364)
- [ ]  Added intermediate saving of data, removing the need for "Save changes"-buttons [Proemion/legacy-windows-software#387](Proemion/legacy-windows-software#387)
- [ ]    Changed input error handling across the whole application
- [ ]  Added a bit coder element to support entering binary values [Proemion/legacy-windows-software#386](Proemion/legacy-windows-software#386)
- [ ]      Added option to close the communication channel [Proemion/legacy-windows-software#404](Proemion/legacy-windows-software#404)
- [ ] Added a check for maximum length of string variables [Proemion/legacy-windows-software#274](Proemion/legacy-windows-software#274)      
- [ ]   Added import of offset and multiplier values to DBC import [Proemion/legacy-windows-software#259](Proemion/legacy-windows-software#259)          
- [ ]     Added an option to change button alignment to left hand [Proemion/legacy-windows-software#388](Proemion/legacy-windows-software#388)           
- [ ] Added an option to change graphical design to legacy design [Proemion/legacy-windows-software#270](Proemion/legacy-windows-software#270)    
- [ ]   Added a note to Calculate Parameter function, in case of memory size mismatch [Proemion/legacy-windows-software#367](Proemion/legacy-windows-software#367)    
- [ ]    Moved DOD information and description to main application page  
- [ ]    Removed baudrate option for 83.333 kBit/s, since it was not supported  [Proemion/legacy-windows-software#342 ](Proemion/legacy-windows-software#342 )    
- [ ]  Removed data type range checking for link variables [Proemion/legacy-windows-software#381](Proemion/legacy-windows-software#381)  [Proemion/legacy-windows-software#380](Proemion/legacy-windows-software#380)
- [ ]     Removed data type range checking for read only variables [Proemion/legacy-windows-software#394](Proemion/legacy-windows-software#394)     
- [ ] Removed warnings when using non-volatile memory [Proemion/legacy-windows-software#385  ](Proemion/legacy-windows-software#385  )  
- [ ]  Changed behavior while opening the communication channel     When clicking on the right hand symbol in the toolbar, the channel will be opened
- [ ]    Changed EDS export format to be more conform to CANopen standard [Proemion/legacy-windows-software#65](Proemion/legacy-windows-software#65)      
- [ ]  Changed the design of all object dictionary entries     
- [ ] Changed the way some errors are being displayed across all object dictionary entries [Proemion/legacy-windows-software#389](Proemion/legacy-windows-software#389) [Proemion/legacy-windows-software#391](Proemion/legacy-windows-software#391)
- [ ]     Reduced time needed to save DOD by 40%  
- [x]   Reduced the impact of product group number warnings while downloading the configuration [Proemion/legacy-windows-software#363](Proemion/legacy-windows-software#363)      
- [ ]  Target/Gateway mode will now only be displayed if supported by the device [Proemion/legacy-windows-software#405 ](Proemion/legacy-windows-software#405)   
- [ ]   Changed the sorting in the configuration device type selection dialogue    
- [ ]    Fixed a bug where non-volatile variables have been transmitted during remote download [Proemion/legacy-windows-software#373](Proemion/legacy-windows-software#373)      
- [ ]   Fixed an invalid pointer operation when creating new Receive CAN Messages [Proemion/legacy-windows-software#343  ](Proemion/legacy-windows-software#343  )    
- [x]   Fixed a bug when saving a configuration while on the Specials tab [Proemion/legacy-windows-software#338 ](Proemion/legacy-windows-software#338 )    
- [ ]   Fixed broken variable references when variable type has been changed   
- [ ]  Fixed a bug when configuring CAN remote frames in Transmit CAN Messages [Proemion/legacy-windows-software#275  ](Proemion/legacy-windows-software#275  )    
- [ ]   Fixed a bug when toggling messages validity in PDO Mapping configuration[Proemion/legacy-windows-software#398 ](Proemion/legacy-windows-software#398 )    
- [ ]    Fixed a bug when configuring logging strings in Operation Manager[Proemion/legacy-windows-software#315]( Proemion/legacy-windows-software#315)  
- [ ]   Fixed a bug when setting BCD time in different country format   [Proemion/legacy-windows-software#354  ](Proemion/legacy-windows-software#354  )   
- [ ]  Fixed a bug where upper and lower boundaries of 32 bit variables where incorrect [Proemion/legacy-windows-software#348](Proemion/legacy-windows-software#348)      
- [ ]   Fixed a bug where new object dictionary entries were not always focused correctly [Proemion/legacy-windows-software#393  ](Proemion/legacy-windows-software#393)  
- [ ] Fixed a bug where 11 bit messages where imported as 29 bit messages in DBC import[Proemion/legacy-windows-software#396 ](Proemion/legacy-windows-software#396 )    
- [ ]  Fixed a bug when entering hex values in Receive CAN Messages logging     
- [ ]  here may be an error when importing certain values from another DOD [Proemion/legacy-windows-software#14](Proemion/legacy-windows-software#14) [Proemion/legacy-windows-software#15](Proemion/legacy-windows-software#15)

**Comment by ss1043** [comment]
- [ ] Updated software branding to reflect the new CI  [Proemion/legacy-windows-software#329](Proemion/legacy-windows-software#329)
- [ ]     Added support for logging J1939 messages [Proemion/legacy-windows-software#364](Proemion/legacy-windows-software#364)
- [ ]  Added intermediate saving of data, removing the need for "Save changes"-buttons [Proemion/legacy-windows-software#387](Proemion/legacy-windows-software#387)
- [ ]    Changed input error handling across the whole application
- [ ]  Added a bit coder element to support entering binary values [Proemion/legacy-windows-software#386](Proemion/legacy-windows-software#386)
- [ ]      Added option to close the communication channel [Proemion/legacy-windows-software#404](Proemion/legacy-windows-software#404)
- [ ] Added a check for maximum length of string variables [Proemion/legacy-windows-software#274](Proemion/legacy-windows-software#274)      
- [ ]   Added import of offset and multiplier values to DBC import [Proemion/legacy-windows-software#259](Proemion/legacy-windows-software#259)          
- [ ]     Added an option to change button alignment to left hand [Proemion/legacy-windows-software#388](Proemion/legacy-windows-software#388)           
- [ ] Added an option to change graphical design to legacy design [Proemion/legacy-windows-software#270](Proemion/legacy-windows-software#270)    
- [ ]   Added a note to Calculate Parameter function, in case of memory size mismatch [Proemion/legacy-windows-software#367](Proemion/legacy-windows-software#367)    
- [ ]    Moved DOD information and description to main application page  
- [ ]    Removed baudrate option for 83.333 kBit/s, since it was not supported  [Proemion/legacy-windows-software#342 ](Proemion/legacy-windows-software#342 )    
- [ ]  Removed data type range checking for link variables [Proemion/legacy-windows-software#381](Proemion/legacy-windows-software#381)  [Proemion/legacy-windows-software#380](Proemion/legacy-windows-software#380)
- [ ]     Removed data type range checking for read only variables [Proemion/legacy-windows-software#394](Proemion/legacy-windows-software#394)     
- [ ] Removed warnings when using non-volatile memory [Proemion/legacy-windows-software#385  ](Proemion/legacy-windows-software#385  )  
- [ ]  Changed behavior while opening the communication channel     When clicking on the right hand symbol in the toolbar, the channel will be opened
- [ ]    Changed EDS export format to be more conform to CANopen standard [Proemion/legacy-windows-software#65](Proemion/legacy-windows-software#65)      
- [ ]  Changed the design of all object dictionary entries     
- [ ] Changed the way some errors are being displayed across all object dictionary entries [Proemion/legacy-windows-software#389](Proemion/legacy-windows-software#389) [Proemion/legacy-windows-software#391](Proemion/legacy-windows-software#391)
- [ ]     Reduced time needed to save DOD by 40%  
- [x]   Reduced the impact of product group number warnings while downloading the configuration [Proemion/legacy-windows-software#363](Proemion/legacy-windows-software#363)      
- [ ]  Target/Gateway mode will now only be displayed if supported by the device [Proemion/legacy-windows-software#405 ](Proemion/legacy-windows-software#405)   
- [ ]   Changed the sorting in the configuration device type selection dialogue    
- [ ]    Fixed a bug where non-volatile variables have been transmitted during remote download [Proemion/legacy-windows-software#373](Proemion/legacy-windows-software#373)      
- [ ]   Fixed an invalid pointer operation when creating new Receive CAN Messages [Proemion/legacy-windows-software#343  ](Proemion/legacy-windows-software#343  )    
- [x]   Fixed a bug when saving a configuration while on the Specials tab [Proemion/legacy-windows-software#338 ](Proemion/legacy-windows-software#338 )    
- [ ]   Fixed broken variable references when variable type has been changed   
- [ ]  Fixed a bug when configuring CAN remote frames in Transmit CAN Messages [Proemion/legacy-windows-software#275  ](Proemion/legacy-windows-software#275  )    
- [ ]   Fixed a bug when toggling messages validity in PDO Mapping configuration[Proemion/legacy-windows-software#398 ](Proemion/legacy-windows-software#398 )    
- [ ]    Fixed a bug when configuring logging strings in Operation Manager[Proemion/legacy-windows-software#315]( Proemion/legacy-windows-software#315)  
- [ ]   Fixed a bug when setting BCD time in different country format   [Proemion/legacy-windows-software#354  ](Proemion/legacy-windows-software#354  )   
- [ ]  Fixed a bug where upper and lower boundaries of 32 bit variables where incorrect [Proemion/legacy-windows-software#348](Proemion/legacy-windows-software#348)      
- [ ]   Fixed a bug where new object dictionary entries were not always focused correctly [Proemion/legacy-windows-software#393  ](Proemion/legacy-windows-software#393)  
- [ ] Fixed a bug where 11 bit messages where imported as 29 bit messages in DBC import[Proemion/legacy-windows-software#396 ](Proemion/legacy-windows-software#396 )    
- [ ]  Fixed a bug when entering hex values in Receive CAN Messages logging     
- [ ]  here may be an error when importing certain values from another DOD [Proemion/legacy-windows-software#14](Proemion/legacy-windows-software#14) [Proemion/legacy-windows-software#15](Proemion/legacy-windows-software#15)
