### ISSUE TITLE
Onsite Week Diogo/Filipe in January 2023

### ISSUE THREAD

**Issue by ss1043** [ss1043/demo#9]
## Scheduled onsite week
Arrival: 15th January,2023 [LH 1177 Y 15JAN OPOFRA HS1 1225  1610]
Departure: 21st January, 2023 [LH 1180 Y 21JAN FRAOPO HS1 2020  2205]

## Who?
- Diogo
- Filipe

## Why?
- Onboarding Diogo, get to know him
- Filipe focus is on CI

## To-Do Before

- [x] Organize tour through the production, already asked Stefan V. https://proemion.slack.com/archives/DG64X03NC/p1671451720825869
- [ ] Evening event with the team? Bowling etc? (one dinner will be payed by PE)
    - private payment, but one evening dinner paid by Proemion 
- [x] Payment for lunch, dinner, event by Proemion, asking HR
     - private payment, but one evening dinner paid by Proemion 
     - one lunch paid by Proemion
     - https://proemion.slack.com/archives/D03NSUX6PNX/p1673534378770289 
- [x] Working place for Filipe and Diogo

## Time line

 | Weekday | Scheduled | Evening
|---|---|---|
|Sunday| Arrival, Hotel| -
|Monday | Arrival at Proemion, HQ Tour, Team meeting| Bowling, Cafe del Sol
|Tuesday | CLW4000 induction, CI maintenance
|Wednesday | Production Tour 11-12am+Lunch?, Setup presentation: CI, E2E, IS test
| Thursday |
| Friday | CC-Hiking tour
| Saturday | Departure

**Comment by ss1043** [comment]
- Annika Glaser cares about flights, hotels etc. 
- She will also ask regarding dinner payment etc.
- Annika also check if the production tour  during the global onboarding day match to the 3rd calendar week

**Comment by ss1043** [comment]
Onsite week was very useful
